# Basic
title: Simon Cheng
subtitle: Product Engineer
description: Building reliable web products with clean engineering.
# 头像里面的标题
avatarTitle: Simon
# 头像里面的描述
avatarDesc: engineer | builder | learner
# 头像图片路径
avatar: /images/simon.jpg
url: "https://codebistro.github.io"

# 博客是否自动生成目录，false为不生成
enableToc: true

# Comment
comment:
    # livere: MTAyMC81MDk5NC8yNzQ3Ng  # https://www.livere.com
    # disqus: leopard
    # uyan: 2143225  # 有言id,登录有言官网申请

# Social
social:
    github: codebistro
    # twitter: 
    mail: itdevelopersimon@gmail.com


# 百度统计 
# 使用博客模板请去掉或者更换 id 
# baidu:
    # id: 8ba1c6be0953b6f9c2ba38e57f615421  

# Google Analytics
# 使用博客模板请去掉或者更换 id
ga:
    id: G-37DJKMS7PK
    host: auto


# 《----------------- 上面的信息修改成你自己的 ---------------------------》
#
#
#  _post/ 下的文章更换成你自己的文章
#  帮忙star一下，感谢~😆 地址： https://github.com/leopardpan/leopardpan.github.io
#
#
# 《--------------- 下面的信息可以自行选择是否修改 ------------------------》


permalink: /:year/:month/:title/
# Format
highlighter: rouge

textColor: #FF0000

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: clear

# The blog button should not be removed.
blog_button:
    title: Portfolio

# Navigation buttons in the front page.s
nav:
    - {title: About, description: about, url: '/#about'}
    - {title: Projects, description: projects, url: '/#projects'}
    - {title: Work History, description: work history, url: '/#resume'}
    - {title: Contact, description: contact, url: '/#contact'}
    

# Pagination
gems: [jekyll-paginate,jekyll-sitemap]
plugins:
    - jekyll-paginate
    - jekyll-sitemap
paginate: 20
paginate_path: "page/:num/"


